params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  caterpillar_3:
    path_to_network_params: trained_models/tutorials/caterpillar_3/003501.pth

dataset: [] # which dataset to use, not used for now

output_dir: analysis
