logs_root_path: code/data_volume/pdc/logs_proto
object_id_list: ["star_bot", "caterpillar", "baymax"]
train:
- "2018-05-04-20-12-25" # singulated (mostly)
- "2018-05-04-20-19-47" # cluttered
- "2018-05-04-20-22-22" # singulated (mostly)
- "2018-05-04-20-35-49" # singulated
2018-05-11-17-18-02 # cluttered
2018-05-11-17-19-45 # cluttered
2018-05-11-17-21-25 # singulated
2018-05-11-17-23-28 # cluttered
2018-05-11-17-25-46 # singulated
2018-05-11-17-28-06 # singulated
2018-05-11-17-33-51 # cluttered - stacked like 3 pancakes
2018-05-11-17-36-28 # cluttered
2018-05-11-17-39-04 # cluttered
2018-05-11-17-41-14 # singulated

test:
- "2018-05-04-20-12-25"
- "2018-05-04-20-19-47"
- "2018-05-04-20-22-22"
- "2018-05-04-20-35-49"
evaluation_labeled_data_path: 
- "code/data_volume/pdc/evaluation_labeled_data/caterpillar_starbot_baymax_multi_cross_scene_labels.yaml"
