qlogs_root_path: logs_proto
object_id: "baymax"
train:
- "2018-04-24-17-16-40" # head pointed down left
- "2018-04-24-17-34-46" # head pointed down
- "2018-04-24-17-38-19" # head pointed up and right
- "2018-05-07-22-04-57" # head pointed up
- "2018-05-11-18-23-21" # head pointing down right
- "2018-05-11-18-21-13" # head pointing right
- "2018-05-11-18-18-57" # head pointing up left
- "2018-05-11-18-17-14" # head pointing left
test:
- "2018-04-24-17-42-27" # head pointed up and right
- "2018-04-24-17-30-08" # head pointed down
evaluation_labeled_data_path:
- "evaluation_labeled_data/baymax_front_cross_scene_labels.yaml"
