logs_root_path: code/data_volume/pdc/logs_proto
object_id: "caterpillar"
train:
- "2018-04-16-14-25-19"
- "2018-04-16-14-40-25"
- "2018-04-16-14-42-26"
- "2018-04-16-14-44-53"
- "2018-04-16-14-49-22"
- "2018-04-16-15-23-41"
- "2018-04-16-15-25-38"
- "2018-04-16-15-28-45"
- "2018-04-16-15-30-50"
test:
- "2018-04-16-14-46-36"
- "2018-04-16-17-35-21"

evaluation_labeled_data_path: 
- "code/data_volume/pdc/evaluation_labeled_data/caterpillar_cross_scene_labels.yaml"
