logs_root_path: logs_proto
object_id: "caterpillar"
train:
- "2018-04-10-16-02-59" # upright
- "2018-04-10-16-04-10" # upright
- "2018-04-10-16-06-26" # upright
- "2018-04-10-16-12-21" # upright
- "2018-04-10-16-13-37" # upright
- "2018-04-10-16-16-15" # crumpled upright
- "2018-04-16-14-25-19" # upright
- "2018-04-16-14-40-25" # upright
- "2018-04-10-16-08-46" #upright, buckles swapped
- "2018-04-16-14-44-53" # upright
- "2018-04-16-15-23-41" # on side facing camera, half upright
test:
- "2018-04-16-14-42-26" # upright
- "2018-04-10-16-11-10" # upright buckles undone
- "2018-04-16-14-46-36" # upright


evaluation_labeled_data_path: 
- "evaluation_labeled_data/caterpillar_cross_scene_labels.yaml"
