logs_root_path: logs_proto
train:
- "05_drill_long_downsampled"
- "06_drill_long_downsampled"
- "07_drill_long_downsampled"
- "08_drill_long_downsampled"
- "09_drill_long_downsampled"
- "10_drill_long_downsampled"
- "11_drill_long_downsampled"
- "12_drill_long_downsampled"
- "13_drill_long_downsampled"
- "2018-04-07-20-22-05"
- "2018-04-07-20-23-56"
- "2018-04-07-21-19-23"
- "2018-04-10-16-02-59"
- "2018-04-10-16-04-10"
- "2018-04-10-16-05-17"
- "2018-04-10-16-06-26"
- "2018-04-10-16-08-46"
- "2018-04-10-16-11-10"
- "2018-04-10-16-12-21"
- "2018-04-10-16-13-37"
- "2018-04-10-16-14-41"
- "2018-04-10-16-16-15"
- "2018-04-12-22-07-29"
- "2018-04-13-14-06-42"
- "2018-04-13-14-07-54"
- "2018-04-13-14-18-27"
- "2018-04-13-14-19-38"
- "2018-04-13-14-22-02"
- "2018-04-13-14-23-14"
- "2018-04-16-14-25-19"
- "2018-04-16-14-40-25"
- "2018-04-16-14-42-26"
- "2018-04-16-14-44-53"
- "2018-04-16-14-46-36"
- "2018-04-16-14-49-22"
- "2018-04-16-15-23-41"
- "2018-04-16-15-25-38"
- "2018-04-16-15-28-45"
- "2018-04-16-15-30-50"
- "2018-04-16-17-35-21"
- "2018-04-23-13-36-51"
- "2018-04-23-13-39-37"
- "2018-04-23-13-42-37"
- "2018-04-23-13-45-36"
- "2018-04-23-13-47-33"
- "2018-04-23-13-49-47"
- "2018-04-23-13-51-51"
- "2018-04-24-15-57-16"
- "2018-04-24-15-59-25"
- "2018-04-24-16-01-23"
- "2018-04-24-16-08-09"
- "2018-04-24-16-09-58"
- "2018-04-24-16-12-18"
- "2018-04-24-16-14-04"
- "2018-04-24-16-16-01"
- "2018-04-24-16-17-53"
- "2018-04-24-16-21-57"
- "2018-04-24-16-24-20"
- "2018-04-24-16-26-12"
- "2018-04-24-16-29-07"
- "2018-04-24-16-30-59"
- "2018-04-24-16-32-53"
- "2018-04-24-16-35-33"
- "2018-04-24-16-37-27"
- "2018-04-24-16-39-23"
- "2018-04-24-16-42-22"
- "2018-04-24-16-46-40"
- "2018-04-24-16-49-18"
- "2018-04-24-16-50-59"
- "2018-04-24-16-53-13"
- "2018-04-24-16-55-07"
- "2018-04-24-16-56-52"
- "2018-04-24-16-58-55"
- "2018-04-24-17-03-43"
- "2018-04-24-17-08-35"
- "2018-04-24-17-10-56"
- "2018-04-24-17-14-34"
- "2018-04-24-17-16-40"
- "2018-04-24-17-18-39"
- "2018-04-24-17-21-47"
- "2018-04-24-17-28-10"
- "2018-04-24-17-30-08"
- "2018-04-24-17-32-36"
- "2018-04-24-17-34-46"
- "2018-04-24-17-38-19"
- "2018-04-24-17-40-34"
- "2018-04-24-17-42-27"
- "2018-04-24-17-46-59"
- "2018-04-24-17-50-15"
- "2018-04-24-17-52-22"
- "2018-04-24-17-54-51"
- "2018-04-24-17-56-42"
- "2018-04-24-17-58-48"
- "2018-04-24-18-00-40"
- "2018-04-24-18-02-34"
- "2018-04-24-18-05-58"
- "2018-04-24-18-07-45"
- "2018-04-24-18-10-31"
- "2018-04-24-18-14-35"
- "2018-04-24-18-16-43"
- "2018-04-24-18-20-17"
- "2018-04-24-18-23-06"
- "2018-04-24-18-26-05"
- "2018-04-24-18-28-16"
- "2018-04-24-18-30-48"
- "2018-04-24-18-33-20"
- "2018-04-24-18-36-29"
- "2018-04-25-17-49-39"
- "2018-04-25-17-52-19"
- "2018-04-25-17-54-11"
- "2018-04-25-17-56-29"
- "2018-04-25-17-59-04"
- "2018-04-25-18-02-21"
- "2018-04-25-18-04-52"
- "2018-04-25-18-06-59"
- "2018-04-25-18-09-08"
- "2018-04-25-18-11-26"
- "2018-04-25-18-14-30"
- "2018-04-25-18-17-18"
- "2018-04-25-18-19-06"
- "2018-04-25-18-24-39"
- "2018-04-25-18-27-45"
- "2018-04-25-18-33-44"
- "2018-04-25-18-37-07"
- "2018-04-25-18-40-49"
- "2018-04-25-18-43-01"
- "2018-04-25-21-09-11"
- "2018-04-25-21-12-15"
- "2018-04-25-21-19-47"
- "2018-05-04-19-42-34"
- "2018-05-04-19-44-47"
- "2018-05-04-19-50-07"
- "2018-05-04-19-52-54"
- "2018-05-04-19-55-17"
- "2018-05-04-20-00-48"
- "2018-05-04-20-04-43"
- "2018-05-04-20-06-40"
- "2018-05-04-20-08-47"
- "2018-05-04-20-10-32"
- "2018-05-04-20-12-25"
- "2018-05-04-20-15-15"
- "2018-05-04-20-17-27"
- "2018-05-04-20-19-47"
- "2018-05-04-20-22-22"
- "2018-05-04-20-24-47"
- "2018-05-04-20-26-53"
- "2018-05-04-20-29-14"
- "2018-05-04-20-35-49"
- "2018-05-04-20-38-23"
- "2018-05-07-18-38-43"
- "2018-05-07-18-46-43"
- "2018-05-07-22-04-57"
- "2018-05-08-16-32-18"
- "2018-05-08-16-51-34"
- "2018-05-08-16-53-55"
- "2018-05-08-16-56-44"
- "2018-05-08-16-59-30"
- "2018-05-08-17-01-55"
- "2018-05-08-17-04-17"
- "2018-05-08-17-06-39"
- "2018-05-08-17-12-30"
- "2018-05-08-17-15-34"
- "2018-05-08-17-18-03"
- "2018-05-08-17-26-26"
- "2018-05-08-17-32-39"
- "2018-05-08-17-34-18"
- "2018-05-08-17-36-07"
- "2018-05-08-17-38-21"
- "2018-05-08-17-40-14"
- "2018-05-08-17-43-26"
- "2018-05-08-17-46-19"
- "2018-05-08-17-48-47"
- "2018-05-09-17-27-32"
- "2018-05-09-17-30-12"
- "2018-05-09-17-32-07"
- "2018-05-09-17-34-32"
- "2018-05-09-17-36-30"
- "2018-05-09-17-43-26"
- "2018-05-09-17-45-21"
- "2018-05-09-17-47-10"
- "2018-05-09-17-49-03"
- "2018-05-09-17-50-59"
- "2018-05-09-17-53-41"
- "2018-05-09-17-56-41"
- "2018-05-09-17-59-10"
- "2018-05-09-18-01-12"
- "2018-05-09-18-04-04"
- "2018-05-09-18-06-07"
- "2018-05-09-18-08-21"
- "2018-05-09-18-10-18"
- "2018-05-09-18-11-53"
- "2018-05-09-18-13-50"
- "2018-05-09-18-16-26"
- "2018-05-09-18-19-27"
- "2018-05-09-18-21-25"
- "2018-05-09-18-23-00"
- "2018-05-09-18-24-54"
- "2018-05-09-18-26-35"
- "2018-05-09-18-29-11"
- "2018-05-09-18-31-52"
- "2018-05-09-18-35-42"
- "2018-05-09-18-39-49"
- "2018-05-09-18-41-43"
- "2018-05-09-18-44-32"
- "2018-05-11-17-00-57"
- "2018-05-11-17-03-18"
- "2018-05-11-17-08-04"
- "2018-05-11-17-18-02"
- "2018-05-11-17-19-45"
- "2018-05-11-17-21-25"
- "2018-05-11-17-23-28"
- "2018-05-11-17-25-46"
- "2018-05-11-17-28-06"
- "2018-05-11-17-33-51"
- "2018-05-11-17-36-28"
- "2018-05-11-17-39-04"
- "2018-05-11-17-41-14"
- "2018-05-11-18-17-14"
- "2018-05-11-18-18-57"
- "2018-05-11-18-21-13"
- "2018-05-11-18-23-21"
- "2018-05-11-18-25-30"
- "2018-05-11-18-27-23"
- "2018-05-11-18-29-31"
- "2018-05-11-18-35-26"
- "2018-05-11-18-37-50"
- "2018-05-11-18-48-40"
- "2018-05-11-18-50-50"
- "2018-05-14-22-10-53"
- "2018-05-14-22-15-08"
- "2018-05-14-22-17-00"
- "2018-05-14-22-19-06"
- "2018-05-14-22-31-21"
- "2018-05-14-22-33-14"
- "2018-05-14-22-35-08"
- "2018-05-14-22-47-49"
- "2018-05-14-22-50-02"
- "2018-05-14-22-52-15"
- "2018-05-14-22-57-40"
- "2018-05-14-23-00-04"
- "2018-05-14-23-02-05"
- "2018-05-14-23-37-43"
- "2018-05-14-23-44-17"
- "2018-05-14-23-46-34"
- "2018-05-15-00-04-06"
- "2018-05-15-00-06-46"
- "2018-05-15-00-08-46"
- "2018-05-15-00-26-19"
- "2018-05-15-00-28-06"
- "2018-05-15-00-29-54"
- "2018-05-15-00-36-25"
- "2018-05-15-00-38-37"
- "2018-05-15-00-40-41"
- "2018-05-15-00-44-37"
- "2018-05-15-00-46-52"
- "2018-05-15-00-49-26"
- "2018-05-15-00-57-24"
- "2018-05-15-00-59-42"
- "2018-05-15-01-01-59"
- "2018-05-15-21-51-52"
- "2018-05-15-21-59-42"
- "2018-05-15-22-01-44"
- "2018-05-15-22-04-17"
- "2018-05-17-00-46-45"
- "2018-05-17-00-49-57"
- "2018-05-17-00-52-30"
- "2018-05-17-00-54-26"
- "2018-05-17-00-56-44"
- "2018-05-17-01-00-14"
- "2018-05-17-01-02-45"
- "2018-05-17-01-11-41"
- "2018-05-18-16-26-26"
- "2018-05-18-16-29-42"
- "2018-05-18-16-32-30"
- "testbag"

test: []