logs_root_path: logs_proto
object_id: "hat_boston_red_sox"
train:
- "2018-04-23-13-36-51" # pointing down
- "2018-05-08-16-32-18" # pointing up
- "2018-05-08-16-51-34" # pointing left
- "2018-05-08-16-53-55" # pointing right up
test:
- "2018-04-23-13-36-51" # pointing down
- "2018-05-08-16-32-18" # pointing up
- "2018-05-08-16-51-34" # pointing left
- "2018-05-08-16-53-55" # pointing right up
evaluation_labeled_data_path: 
- "nowhereyet"
