logs_root_path: logs_proto
object_id: "mug"
train:
- "2018-05-09-17-32-07"
- "2018-05-09-17-34-32"
- "2018-05-09-17-36-30"
- "2018-05-09-17-43-26"
- "2018-05-09-17-45-21"
- "2018-05-09-17-47-10"
- "2018-05-09-17-49-03"
- "2018-05-09-17-50-59"
- "2018-05-09-17-53-41"
- "2018-05-09-17-56-41"
- "2018-05-09-17-59-10"
- "2018-05-09-18-01-12"
- "2018-05-14-22-31-21" # 'the best coffee'
- "2018-05-14-22-33-14" # 'the best coffee'
- "2018-05-14-22-35-08" # 'the best coffee'
- "2018-05-14-22-47-49" # brown mug
- "2018-05-14-22-50-02" # brown mug
- "2018-05-14-22-52-15" # brown mug
- "2018-05-15-00-36-25" # red cup
- "2018-05-15-00-38-37" # red cup
- "2018-05-15-00-40-41" # red cup
- "2018-05-15-00-44-37" # 'you're dreamy mug'
- "2018-05-15-00-46-52" # 'you're dreamy mug'
- "2018-05-15-00-49-26" # 'you're dreamy mug'
- "2018-05-15-00-57-24" # 'the best coffee'
- "2018-05-15-01-01-59" # 'the best coffee'
- "2018-05-15-00-59-42" # 'the best coffee'
- "2019-02-15-03-47-38"
- "2019-02-15-02-46-12"
- "2019-02-15-02-18-39"
- "2019-02-15-03-22-39"
- "2019-02-15-03-57-26"
- "2019-02-15-02-24-32"
- "2019-02-15-02-55-19"
- "2019-02-15-03-41-40"
- "2019-02-15-03-11-39"
- "2019-02-15-03-01-09"
- "2019-02-15-03-28-24"
- "2019-02-15-03-33-32"
- "2019-02-15-04-02-12"
- "2019-02-15-01-45-12"
- "2019-02-15-03-16-31"
- "2019-02-15-03-52-36"
- "2019-02-15-02-40-44"
- "2019-02-15-02-09-35"
- "2019-02-15-02-29-53"
- "2019-02-15-02-34-50"
- "2019-02-21-02-53-49"
- "2019-02-21-02-34-07"
- "2019-02-21-02-43-12"
- "2019-02-21-02-09-39"
- "2019-02-21-03-09-14"
- "2019-02-21-03-29-44"
- "2019-02-21-02-59-15"
- "2019-02-21-02-05-10"
- "2019-02-21-01-41-16"
- "2019-02-21-03-40-17"
- "2019-02-21-01-59-28"
- "2019-02-21-03-19-28"
- "2019-02-21-02-14-04"
- "2019-02-21-03-24-18"
- "2019-02-21-01-36-08"
- "2019-02-21-03-35-24"
- "2019-02-21-01-53-11"
- "2019-02-21-02-18-51"
- "2019-02-21-01-46-39"
- "2019-02-21-02-48-17"
- "2019-02-21-03-14-14"
- "2019-02-21-02-29-12"
- "2019-02-21-01-31-04"
- "2019-02-21-03-03-53"
- "2019-02-21-02-38-21"
- "2019-02-21-02-23-57"
- "2019-02-21-01-22-32"


test:
- "2018-05-09-17-27-32"
- "2018-05-09-17-30-12"
evaluation_labeled_data_path: 
- "nowhereyet"
