logs_root_path: logs_proto
object_id: "red_bowl"
train:
- "2018-05-11-17-00-57"
- "2018-05-11-17-03-18"
- "2018-05-11-17-08-04"
test:
- "2018-05-11-17-08-04"
# 2018-05-09-18-39-49 bottom got masked out
# 2018-05-09-18-41-43 bottom got masked out
# 2018-05-09-18-44-32 bottom got masked out
evaluation_labeled_data_path: 
- "nowhereyet"