logs_root_path: code/data_volume/pdc/logs_proto
object_id: "shoes"
train:
- "2018-05-09-18-04-04"
- "2018-05-09-18-06-07"
- "2018-05-09-18-08-21"
- "2018-05-09-18-10-18"
- "2018-05-09-18-11-53"
- "2018-05-09-18-13-50"
- "2018-05-09-18-16-26"
- "2018-05-09-18-19-27"
- "2018-05-09-18-21-25"
- "2018-05-09-18-23-00"
- "2018-05-09-18-24-54"
- "2018-05-09-18-31-52"
- "2018-05-09-18-35-42"
- "2018-05-14-22-57-40" # brown boot
- "2018-05-14-23-00-04" # brown boot
- "2018-05-14-23-02-05" # brown boot
- "2018-05-14-23-37-43" # brown boot
- "2018-05-14-23-44-17" # brown boot
- "2018-05-14-23-46-34" # brown boot
- "2018-05-15-00-04-06" # green nike
- "2018-05-15-00-06-46" # green nike
- "2018-05-15-00-08-46" # green nike
- "2018-05-15-00-26-19" # gray nike
- "2018-05-15-00-28-06" # gray nike
- "2018-05-15-00-29-54" # gray nike
test:
- "2018-05-09-18-26-35"
- "2018-05-09-18-29-11"
evaluation_labeled_data_path: 
- "nowhereyet"
