logs_root_path: code/data_volume/pdc/logs_proto
train:
- "2018-04-10-16-02-59"
- "2018-04-10-16-04-10"
- "2018-04-10-16-05-17"
- "2018-04-10-16-06-26"
- "2018-04-10-16-12-21"
- "2018-04-10-16-13-37"
- "2018-04-10-16-14-41"
- "2018-04-10-16-16-15"
test:
- "2018-04-10-16-08-46"
- "2018-04-10-16-11-10"

image_normalization:
  mean: [0.5512, 0.3818, 0.3821]
  std_dev: [0.2303, 0.2753, 0.2867]

