logs_root_path: code/data_volume/pdc/logs_proto
train:
- "05_drill_long_downsampled"
- "07_drill_long_downsampled"
- "08_drill_long_downsampled"
- "09_drill_long_downsampled"
- "10_drill_long_downsampled"
- "12_drill_long_downsampled"
- "13_drill_long_downsampled"
test:
- "06_drill_long_downsampled"
- "11_drill_long_downsampled"

image_normalization:
 mean: [0.5806, 0.4531, 0.4439]
 std_dev: [0.2477, 0.2948, 0.3109]