logs_root_path: code/data_volume/pdc/logs_proto
train:
- "2018-04-24-16-49-18"
- "2018-04-24-16-50-59"
- "2018-04-24-16-53-13"
- "2018-04-24-16-58-55"
- "2018-04-24-17-03-43"
- "2018-04-24-17-08-35"
- "2018-04-24-17-10-56"
- "2018-04-24-17-14-34"
test:
- "2018-04-24-16-55-07"
- "2018-04-24-16-56-52"
