logs_root_path: code/data_volume/pdc/logs_proto
train:
- "2018-04-10-16-02-59"
- "2018-04-10-16-04-10"
- "2018-04-10-16-05-17"
- "2018-04-10-16-06-26"
- "2018-04-10-16-12-21"
- "2018-04-10-16-13-37"
- "2018-04-10-16-14-41"
- "2018-04-10-16-16-15"
- "2018-04-16-14-25-19"
- "2018-04-16-14-40-25"
- "2018-04-16-14-42-26"
- "2018-04-16-14-44-53"
- "2018-04-16-14-49-22"
- "2018-04-16-15-23-41"
- "2018-04-16-15-25-38"
- "2018-04-16-15-28-45"
- "2018-04-16-15-30-50"
test:
- "2018-04-10-16-08-46"
- "2018-04-10-16-11-10"
- "2018-04-16-14-46-36"
- "2018-04-16-17-35-21"